spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8080

#Secret Key
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

#Register as Eureka client
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost