pipeline {
  agent any

  environment {
    VERSION = "${env.BUILD_ID}"
  }

  tools {
    maven "Maven"
  }

  stages {

    stage('Maven Build'){
      steps{
        sh 'mvn clean install'
      }
    }

     stage('Run Tests') {
       steps {
         sh 'mvn test'
       }
     }

     stage('Docker Build') {
        steps {
            sh 'docker build -t abhigupta3/service-registry:${VERSION} .'
        }
     }

}
